//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mota
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:e3fd943f-6cd3-4a52-9da8-7580621aa5fe
    public partial class UIGamePanel
    {
        
        public const string NAME = "UIGamePanel";
        
        private UIGamePanelData mPrivateData = null;
        
        public UIGamePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIGamePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            mData = null;
        }
    }
}
