//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:f1550d60-ee76-4e1f-9628-2e6e7e703e71
    public partial class UIHomePanel
    {
        
        public const string NAME = "UIHomePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnStartGame;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnContinue;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnQuit;
        
        private UIHomePanelData mPrivateData = null;
        
        public UIHomePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIHomePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnStartGame = null;
            BtnContinue = null;
            BtnQuit = null;
            mData = null;
        }
    }
}
